### ISSUE TITLE
variables in functions

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/tes_spatial_access#5]
@bpbond 

I need to calculate the p-values for _many_ sets of nested variables, so I created a function to reproduce it.

**Effect of moisture on `counts`, for each suction**

```
compute_pvalues_counts_moisture = function(dat){
  a1 = aov(log(counts) ~ Moisture, data = dat)
  broom::tidy(a1) %>% 
    filter(term != "Residuals") 
}
peakcounts_core %>% 
  group_by(Suction) %>% 
  do(compute_pvalues_counts_moisture(.))
```

| Suction|term     | df|     sumsq|    meansq|  statistic|  p.value|
|-------:|:--------|--:|---------:|---------:|----------:|--------:|
|     1.5|Moisture |  1| 99.821276| 99.821276| 62.1550735| 0.000000|
|    50.0|Moisture |  1|  1.204643|  1.204643|  0.7513581| 0.386538|

The function above works fine, but it allows me to change only the data file (`dat`), but I'd also like to change the response variable, instead of hard-coding `counts` into the script.

essentially, something like:

```
compute_pvalues_counts_moisture = function(dat, VARIABLE){
  a1 = aov(log(VARIABLE) ~ Moisture, data = dat)
...
}
```
and then I somehow specify what the `VARIABLE` is each time I want to run the function 

```
peakcounts_core %>% 
  group_by(Suction) %>% 
  do(compute_pvalues_counts_moisture(., counts))
```

^^Unfortunately, this doesn't work. Do you know how to fix this so I can set `VARIABLE` in the function?

**Comment by bpbond** [comment]
A couple possibilities. One would be
```R
compute_pvalues_counts_moisture <- function(depvar, Moisture) {
  a1 <- aov(log(VARIABLE) ~ Moisture, data = dat)
...
}

peakcounts_core %>% 
  group_by(Suction) %>% 
  do(compute_pvalues_counts_moisture(.$counts, .$Moisture))
```

```
> dat <- data.frame(group = 1:2, counts = runif(20), moisture = runif(20))
> library(dplyr)
> library(broom)
> compute_pvalues_counts_moisture <- function(depvar, Moisture) {
+     a1 <- aov(log(depvar) ~ Moisture, data = dat)
+     broom::tidy(a1) %>% 
+         filter(term != "Residuals")
+ }
> dat %>% 
+     group_by(group) %>% 
+     do(compute_pvalues_counts_moisture(.$counts, .$moisture))
# A tibble: 2 x 7
# Groups:   group [2]
  group term        df  sumsq meansq statistic p.value
  <int> <chr>    <dbl>  <dbl>  <dbl>     <dbl>   <dbl>
1     1 Moisture     1 0.0415 0.0415    0.0499   0.829
2     2 Moisture     1 0.581  0.581     0.628    0.451
```

**Comment by kaizadp** [comment]
Thanks! That worked, kind of.
I had to remove the `data=dat` argument in the function. Which I guess is fine, if I'm piping the function into the `dat` file.

**Comment by kaizadp** [comment]
got it:

```
compute_pvalues_counts_moisture = function(dat, depvar, Moisture){
  a1 = aov(log(depvar) ~ Moisture, data = dat)
  broom::tidy(a1) %>% 
    filter(term != "Residuals") 
}

peakcounts_core %>% 
  group_by(Suction) %>% 
  do(compute_pvalues_counts_moisture(., .$counts, .$Moisture))
```

Thanks!

**Comment by bpbond** [comment]
You shouldn’t need to pass entire data frame, just get rid of `data=...` but anyway great

________________________________
