### ISSUE TITLE
more functions/drake

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/tes_spatial_access#6]
@bpbond 

I'm having trouble with some targets in my `drake` plan. I am trying to make scatterplots with p-values, TukeyHSD letters included.

But I keep getting errors:

https://github.com/kaizadp/tes_spatial_access/blob/5f34b22e8bf9d72448d70f224ba426224896f850/code/2e-fticr_drake_plan.R#L106-L107

> x fail gg_totalcounts
Error: target gg_totalcounts failed.
diagnose(gg_totalcounts)$error$message:
  object 'peakcounts_core' not found

https://github.com/kaizadp/tes_spatial_access/blob/5f34b22e8bf9d72448d70f224ba426224896f850/code/2e-fticr_drake_plan.R#L156

> x fail relabund_coresrelabund_scatterplots
Error: target relabund_coresrelabund_scatterplots failed.
diagnose(relabund_coresrelabund_scatterplots)$error$message:
  object 'relabund_cores_complex' not found

^^^

These targets are linked to functions in the `2f-fticr-pipeline_plotting.R` script (links below). If I run the functions outside of `drake`, they work fine. But when I run the `drake` plan, it breaks. It may be because of the way I have written the functions? Also, the `do_gg_totalcounts` function is the final step in a line of functions, maybe that causes it to break in `drake`?

https://github.com/kaizadp/tes_spatial_access/blob/5f34b22e8bf9d72448d70f224ba426224896f850/code/2f-fticr-pipeline_plotting.R#L293

https://github.com/kaizadp/tes_spatial_access/blob/5f34b22e8bf9d72448d70f224ba426224896f850/code/2f-fticr-pipeline_plotting.R#L414

**Comment by kaizadp** [comment]
These are the plots it should create:

![fticr_totalpeaks_scatter-1](https://user-images.githubusercontent.com/50244730/92826889-33a4a800-f39f-11ea-9809-3bed25a14d8d.png)

![fticr_relabund_complex-1](https://user-images.githubusercontent.com/50244730/92826870-2e475d80-f39f-11ea-83a2-0d6efdbff46e.png)

**Comment by bpbond** [comment]
Wow, you've really got a namespace problem. Something is using the `plyr` package, but you're also using `dplyr` throughout, and I'm getting namespace collisions (e.g. `summarize()` calls are using plyr in some circumstances, which is _not_ what you want and generates errors). That's one problem, and it's causing a lot of others.

To your question: the `gg_totalcounts` target calls `do_gg_totalcounts`, and here's the beginning of that routine:
```R
do_gg_totalcounts <- function(peakcounts_core) {
  browser()
  totalcounts_label <- 
    peakcounts_core %>% 
    do_labels_totalcounts_intact(.$counts, .$Moisture, .$Amendments)
```
This is already looking weird and bad, but look at `do_label_totalcounts_intact`:
```R
do_labels_totalcounts_intact = function(depvar, Moisture, Amendments, Wetting){
  # 1. p-values for moisture ----
  moisture_label = 
    peakcounts_core %>% 
```
The parameters don't match up, and the function is calling `peakcounts_core` which _doesn't exist in this function_. So yeah at this point the code throws up its hand and says wtf.

**Comment by bpbond** [comment]
I'm opening a PR with fixes for some of the above. In particular look at my changes to `2f-fticr-pipeline_plotting.R`. The pipeline now makes it through the R Markdown targets.

**Comment by kaizadp** [comment]
That makes sense, I think. I assumed I didn't have to add the file name in the function structure, because that isn't changing. I guess not.
Thanks!

**Comment by bpbond** [comment]
Question for you: how to you get those very nice looking file references in your comments?

I mean these:
![Screen Shot 2020-09-11 at 1 19 07 PM](https://user-images.githubusercontent.com/1956468/92954403-64352200-f431-11ea-93c6-3ab4175fd944.png)

**Comment by kaizadp** [comment]
I get the permalink from the code file, and then add a line range
example: 
https://github.com/kaizadp/tes_spatial_access/blob/5f34b22e8bf9d72448d70f224ba426224896f850/code/2f-fticr-pipeline_plotting.R #L414-L416
I added the space before the # so you can see the link

https://github.com/kaizadp/tes_spatial_access/blob/5f34b22e8bf9d72448d70f224ba426224896f850/code/2f-fticr-pipeline_plotting.R#L414-L416

**Comment by bpbond** [comment]
Oh cool, thanks.
